name: Build and Test

on:
  push:
    branches: [master,ci]
  pull_request: 
    branches: [master]

env:
  SOLANA_VERSION: 1.8.2

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/install-linux-build-deps
      - uses: ./.github/actions/install-solana
        with: 
          solana_version: ${{ env.SOLANA_VERSION }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        run: yarn install

      - name: Launch local Validator
        run: |
          solana-test-validator -r > /dev/null &
          sleep 2 

      - name: Run Tests
        run: yarn test
